Error: /home/anonimito/work/open-source/jive/server/test/evaluate/commonjs/input-6.js: /home/anonimito/work/open-source/jive/server/test/evaluate/commonjs/input-5.js: Unexpected: default export: ClassExpression
    at unexpected (/home/anonimito/work/open-source/jive/server/src/engine.ts:609:9)
    at PluginPass.ExportDefaultDeclaration (/home/anonimito/work/open-source/jive/server/src/engine.ts:508:18)
    at newFn (/home/anonimito/work/open-source/jive/server/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/home/anonimito/work/open-source/jive/server/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/home/anonimito/work/open-source/jive/server/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/home/anonimito/work/open-source/jive/server/node_modules/@babel/traverse/lib/path/context.js:100:31)
    at TraversalContext.visitQueue (/home/anonimito/work/open-source/jive/server/node_modules/@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitMultiple (/home/anonimito/work/open-source/jive/server/node_modules/@babel/traverse/lib/context.js:72:17)
    at TraversalContext.visit (/home/anonimito/work/open-source/jive/server/node_modules/@babel/traverse/lib/context.js:129:19)
    at Function.traverse.node (/home/anonimito/work/open-source/jive/server/node_modules/@babel/traverse/lib/index.js:82:17)